repos:
- repo: https://github.com/cpplint/cpplint
  rev:  2.0.2
  hooks:
    - id: cpplint
      args:
        - --filter=-legal/copyright,-whitespace/line_length,-whitespace/parens,-whitespace/indent,-whitespace/comments